version: '3.8'
services:
    php:
        image: serversideup/php:8.2-fpm-nginx
        ports:
            - 8080:80
        environment:
            SSL_MODE: 'off'
        volumes:
            - ./:/var/www/html
